### ISSUE TITLE
Add Sudachi again

### ISSUE THREAD

**Issue by FirstS0ul** [RJNY/Obtainium-Emulation-Pack#10]
Hi,

Sudachi is back with an new Website and everything ;-) 

https://github.com/emuplace/sudachi.emuplace.app/releases

Thanks!

**Comment by FirstS0ul** [comment]
Forget it... Installed it manually, its an older version... slighty a copy of yuzu.

**Comment by GlazedBelmont** [comment]
got a new update and now can be added again

**Comment by RJNY** [comment]
I've given this some long thought and decided I'm going to leave switch emulation out of this repo for a while.
