### ISSUE TITLE
Add CEMU

### ISSUE THREAD

**Issue by GlazedBelmont** [RJNY/Obtainium-Emulation-Pack#11]
https://github.com/SSimco/Cemu/releases

**Comment by RJNY** [comment]
I've been tracking the [XForYouX/Cemu-Adroid](https://github.com/XForYouX/Cemu-Android/releases) repo but looks like that one isn't the true one?

I'll plan to add SSimco's sometime this week or next.

**Comment by GlazedBelmont** [comment]
yeah the xforyoux one builds from SSimco's

**Comment by RJNY** [comment]
Cemu was added with commit 74c2df9 and will go out with the next release
