### ISSUE TITLE
ScummVM download: could not find suitable release

### ISSUE THREAD

**Issue by bservet** [RJNY/Obtainium-Emulation-Pack#13]
It does detect my manually installed version but when I try to update I get the error:

RangeError (start): invalid value: Not in inclusive range 0..01:-1

Please note that there's a 2.9.0 folder on the server which currently does not contain an android build. So it should detect that I'm already have the latest version installed.

**Comment by bservet** [comment]
The error has disappeared now that the 2.9.0 folder contains an android build.

**Comment by RJNY** [comment]
Sorry for the late reply, was on vacation.
Thanks for reporting the issue. Glad to hear this is working (for now). This could technically be resolved by checking the "use fallback" option, but that only silences the error, it doesn't really fix the problem. At its heart, this is just a dumb scraper, so any changes that breaks the established pattern will break the scripts. Let me know if this happens again and I'll see what I can do.
