### ISSUE TITLE
[Feature Request] Some emulator ideas that can be added

### ISSUE THREAD

**Issue by MoTem** [RJNY/Obtainium-Emulation-Pack#2]
This is a great initiative! Some ideas on emulators you can consider adding. 

Winulator
https://github.com/brunodev85/winlator/releases
Current most popular windows emulator 

Citra Enhanced
https://github.com/Gamer64ytb/Citra-Enhanced/releases
It seems to be the current active citra fork

**Comment by GlazedBelmont** [comment]
+1 for Winlator

**Comment by RJNY** [comment]
- Winlator has been added.
- Moved Citra discussion to https://github.com/RJNY/Obtainium-Emulation-Pack/issues/6#issue-2324302890
