### ISSUE TITLE
[Feature Request] Adding PPSSPP

### ISSUE THREAD

**Issue by privateemu** [RJNY/Obtainium-Emulation-Pack#4]
This may be difficult to do, not sure Obtanium is capable yet it seems flexible for custom scripts off GitHub, but it would be wonderful if this script could add the ability to autoupdate [PPSSPP's buildbot builds](https://www.ppsspp.org/devbuilds/). They're hosted on ppsspp's website, not GitHub, so it will be more difficult.

**Comment by privateemu** [comment]
There's some discussion on the Obtanium main repo on this: https://github.com/ImranR98/Obtainium/issues/629

**Comment by privateemu** [comment]
The PPSSPP main build has been added to the Obtainum list of apps:

`{"id":"org.ppsspp.ppsspp","url":"https://www.ppsspp.org/download/","author":"PPSSPP","name":"PPSSPP","additionalSettings":"{\"about\":\"PPSSPP is an open source, fast and portable PSP emulator\",\"appName\":\"PPSSPP\",\"customLinkFilterRegex\":\"\\\\/[0-9]+(?:_[0-9]+){1,2}\\\\/ppsspp\\\\.apk$\",\"filterByLinkText\":false,\"matchGroupToUse\":\"$1$3.$2$4$6$5\",\"reverseSort\":false,\"skipSort\":false,\"sortByLastLinkSegment\":false,\"trackOnly\":false,\"useVersionCodeAsOSVersion\":false,\"versionDetection\":true,\"versionExtractWholePage\":false,\"versionExtractionRegEx\":\"\\\\/(?:(?:([0-9]+)_([0-9]+)\\\\/ppsspp\\\\.)|(?:([0-9]+)_([0-9]+)_([0-9]+)\\\\/ppsspp(\\\\.)))apk$\"}","overrideSource":"HTML"}`

I'm trying to modify it to detect the dev builds

**Comment by RJNY** [comment]
Thanks for your suggestion and patience.

So I did a 15 minute investigation on this and mostly thanks to all the resource you shared, I was able to come up with a solution I think _might_ work. 

So if I `curl` their [development page](https://www.ppsspp.org/devbuilds/), the page is not generated by the backend, so it doesn't give us anything useful to regex. That would suggest that the page is generated by the front-end. With that in mind, I took a look at the dev tools network tab and this link popped out to me: https://builds.ppsspp.org/meta/history-20.json

This is just a theory, but I think we can do the following:
- use this as the preliminary link:  https://builds.ppsspp.org/meta/history-20.json
- Set the `latest_version = response[0].description`
- use the `latest_version` to populate the download link like so: `https://builds.ppsspp.org/builds/${latest_version}/ppsspp.apk

I would have to still apply this logic to an obtainium script, but what are your thoughts?

**Comment by RJNY** [comment]
Actually, I don’t see a good way to grab and set variables from preliminary links. If that’s not supported, this method can’t work either.

**Comment by RJNY** [comment]
I've added PPSSPP in the latest release (v3.1.0)
Let me know if that satisfies this feature request

**Comment by privateemu** [comment]
Yeah, I was trying to dig into this as well, I managed to get a RegEx which _should_ batch ` \/v[0-9]+(?:\.[0-9]+){1,2}-[0-9]+-g[0-9a-f]+\/ppsspp\.apk$` however as you found, it doesn't load the links in a good manner, so I don't think there's a good way to get the dev builds at the moment, would require the PPSSPP devs to change something on their end, so the stable build is the best we can do, thanks for adding it!

**Comment by jesstelford** [comment]
If it's at all useful, I came up with a slightly different regex for PPSSPP stable builds:

`{"id":"org.ppsspp.ppsspp","url":"https://www.ppsspp.org/download","author":"www.ppsspp.org","name":"PPSSPP","preferredApkIndex":0,"additionalSettings":"{\"intermediateLink\":[],\"customLinkFilterRegex\":\"ppsspp.apk$\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":false,\"versionExtractWholePage\":false,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36\"}],\"defaultPseudoVersioningMethod\":\"APKLinkHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"(\\\\d+)(_(\\\\d+)(_(\\\\d+))?)?/ppsspp.apk\",\"matchGroupToUse\":\"$1.$3.$5\",\"versionDetection\":true,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"PPSSPP\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"supportFixedAPKURL\":false}"}`
