### ISSUE TITLE
[Discussion] Various Citra Forks

### ISSUE THREAD

**Issue by privateemu** [RJNY/Obtainium-Emulation-Pack#6]
I don't particularly know which is best, but some people do have strong preferences of the various Citra forks:

* https://github.com/PabloMK7/citra
* https://github.com/CitraEnhanced/citra
* https://github.com/weihuoya/citra 

I see them recommended fairly regularly on /r/EmulationOnAndroid. Might be worth including them? Though easily an argument could be made to give the dust another few months to settle to see which stay active amongst the lot.

**Comment by marceloMedeiros** [comment]
+1 for this, specially the PabloMK7 fork, since they are a former dev for citra (proper).

**Comment by GlazedBelmont** [comment]
+1 for Pablo's fork and weihuoya's (also known as Citra MMJ)

**Comment by RJNY** [comment]
I'm not against variants, but I do think that 4 different types of 3DS emulators in the pack may be a bit much.

Is there a community preferred 3DS emulator? And how are these different than Lime3DS?

**Comment by marceloMedeiros** [comment]
> I'm not against variants, but I do think that 4 different types of 3DS emulators in the pack may be a bit much.
> 
> Is there a community preferred 3DS emulator? And how are these different than Lime3DS?

Pablo is a former Citra (proper) developer, so his fork is my personal favorit. CitraMMJ is a fork of Citra well know for its (android only) speedhacks and performance improvements in general, which can be very impactful when running on weaker devices.

Not sure about the other ones though.

**Comment by RJNY** [comment]
So while I think I prefer keeping the most popular option as part of the emulation pack, I contributed to the crowdsource with your requests:

https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/124

Closing this issue in hopes that's an acceptable resolution. Feel free to reopen if you still believe Citra deserves a spot in the emulation pack

**Comment by privateemu** [comment]
That makes sense, appreciate you investigating this and I think adding it to the obtanium main distro is a good solution.

**Comment by RJNY** [comment]
My PR recently went live: https://apps.obtainium.imranr.dev/?categories=emulator
